use BI_PROJETO_INTEGRADOR
--MELHOR VENDEDOR NO ANO 
SELECT NOME_VEND, ANO , NOME_PRODUTO, COUNT (*) AS QUANTIDADE_VENDIDA , SUM(VALOR_VENDA-CUSTO_VENDA) AS LUCRO_LIQUIDO FROM DIM_FATO_VENDAS
INNER JOIN DIM_QUANDO_VENDEU ON COD_QUANDO_VENDEU = COD_QUANDO_VENDEU_F
INNER JOIN DIM_QUEM_VENDEU ON COD_MATRICULA = COD_MATRICULA_F
inner join DIM_O_QUE_PRODUTO on COD_PRODUTO = COD_PRODUTO_F
GROUP BY NOME_VEND, ANO,NOME_PRODUTO 


-- 1) RELATÓRIO QUANTIDADE DE PEÇAS VENDIDA POR REGIÃO E QUEM FORNECEU 
select NOME_PRODUTO, BAIRRO_CLIENTE, COUNT (QUANTIDADE_VENDA) as QUANTIDADE_VENDIDA, NOME_FORNECEDOR from DIM_FATO_VENDAS
inner join DIM_ONDE_CLIENTE on COD_ONDE_CLIENTE = COD_ONDE_CLIENTE_F
inner join DIM_O_QUE_PRODUTO on COD_PRODUTO = COD_PRODUTO_F
inner join DIM_QUEM_FORNECEU on COD_FORNECEDOR = COD_FORNECEDOR_F
group by NOME_PRODUTO,BAIRRO_CLIENTE, NOME_FORNECEDOR,BAIRRO_FORNECEDOR
order by QUANTIDADE_VENDIDA desc

-- 2A) RELATÓRIO DE PEÇAS COMPRADAS SEGREGADAS POR SEXO E FABRICANTE DO AUTOMOVEL 
select SEXO_CLIENTE, NOME_PRODUTO, FABRICANTE_AUTOMOVEL,count(*)as QUANTIDADE, SUM (VALOR_VENDA-CUSTO_VENDA) LUCRO_LIQUIDO , ANO from DIM_FATO_VENDAS 
inner join DIM_O_QUE_PRODUTO on COD_PRODUTO = COD_PRODUTO_F
inner join DIM_QUEM_COMPROU on COD_CLIENTE = COD_CLIENTE_F
inner join  DIM_QUANDO_VENDEU on COD_QUANDO_VENDEU = COD_QUANDO_VENDEU_F
group by SEXO_CLIENTE,NOME_PRODUTO, FABRICANTE_AUTOMOVEL,ANO
order by LUCRO_LIQUIDO DESC

--2B) PEÇAS QUE TEM MAIOR DEMANDA / DEFEITO -- UPDATE BATENTE SUSPESAO
select SEXO_CLIENTE, NOME_PRODUTO, NOME_FORNECEDOR,count(*)as QUANTIDADE, SUM (VALOR_VENDA-CUSTO_VENDA) LUCRO_LIQUIDO , ANO from DIM_FATO_VENDAS 
inner join DIM_O_QUE_PRODUTO on COD_PRODUTO = COD_PRODUTO_F
inner join DIM_QUEM_COMPROU on COD_CLIENTE = COD_CLIENTE_F
inner join  DIM_QUANDO_VENDEU on COD_QUANDO_VENDEU = COD_QUANDO_VENDEU_F
inner join DIM_QUEM_FORNECEU on COD_FORNECEDOR = COD_FORNECEDOR_F
group by SEXO_CLIENTE,NOME_PRODUTO, NOME_FORNECEDOR,ANO
order by LUCRO_LIQUIDO desc 

--2c) IDADE DE CLIENTES QUE MAIS PROPORCIONAM LUCRO PARA A EMPRESA
select DATEDIFF(YEAR,DATA_NASCIMENTO, GETDATE()) AS IDADE_CLIENTE, NOME_PRODUTO, FABRICANTE_AUTOMOVEL,count(*)as QUANTIDADE, SUM (VALOR_VENDA-CUSTO_VENDA) LUCRO_LIQUIDO , ANO from DIM_FATO_VENDAS 
inner join DIM_O_QUE_PRODUTO on COD_PRODUTO = COD_PRODUTO_F
inner join DIM_QUEM_COMPROU on COD_CLIENTE = COD_CLIENTE_F
inner join  DIM_QUANDO_VENDEU on COD_QUANDO_VENDEU = COD_QUANDO_VENDEU_F
group by  DATEDIFF(YEAR,DATA_NASCIMENTO, GETDATE()),NOME_PRODUTO, FABRICANTE_AUTOMOVEL,ANO
order by LUCRO_LIQUIDO DESC


--3) RELATÓRIO NOVOS CLIENTES DA EMPRESA, IMPLEMENTAÇÃO DE OFERECER MAIS PRODUTOS  POR EMAIL RELACIONADOS A COMPRA REALIZADA
select DISTINCT NOME_CLIENTE, EMAIL_CLIENTE,NOME_PRODUTO,APLICACAO_PRODUTO,BAIRRO_CLIENTE from DIM_FATO_VENDAS
inner join DIM_QUEM_COMPROU on COD_CLIENTE = COD_CLIENTE_F
inner join DIM_O_QUE_PRODUTO on COD_PRODUTO = COD_PRODUTO_F
inner join DIM_ONDE_CLIENTE on COD_ONDE_CLIENTE = COD_ONDE_CLIENTE_F
where PRIMEIRA_COMPRA_CLIENTE = 1

--4) VENDEDOR QUE MAIS VENDEU DETERMINDADA PEÇA
SELECT NOME_VEND, NOME_PRODUTO, count (*)as QUANTIDADE, SUM (VALOR_VENDA-CUSTO_VENDA) as LUCRO_LIQUIDO , MES FROM DIM_FATO_VENDAS
inner join DIM_QUEM_VENDEU ON COD_MATRICULA = COD_MATRICULA_F
inner join DIM_O_QUE_PRODUTO on COD_PRODUTO = COD_PRODUTO_F
inner join DIM_QUANDO_VENDEU ON COD_QUANDO_VENDEU = COD_QUANDO_VENDEU_F
group by NOME_VEND, NOME_PRODUTO, MES
order by QUANTIDADE desc

-- 5 ) QUANTIDADE DE PEÇAS VENDIDAS POR MES
SELECT NOME_PRODUTO, count (*) AS QUANTIDADE_VENDIDA, ANO,BAIRRO_CLIENTE FROM DIM_FATO_VENDAS
inner join DIM_ONDE_CLIENTE on COD_ONDE_CLIENTE = COD_ONDE_CLIENTE_F
inner join DIM_O_QUE_PRODUTO on COD_PRODUTO = COD_PRODUTO_F
inner join DIM_QUANDO_VENDEU on COD_QUANDO_VENDEU = COD_QUANDO_VENDEU_F
group by NOME_PRODUTO,ANO,BAIRRO_CLIENTE
ORDER BY QUANTIDADE_VENDIDA DESC

--6)VENDAS ESPECILIZADAS POR VENDEDOR
SELECT NOME_FORNECEDOR, NOME_PRODUTO, NOME_VEND, COUNT (*) QUANTIDADE_VENDIDA FROM DIM_FATO_VENDAS
INNER JOIN DIM_QUEM_FORNECEU ON COD_FORNECEDOR = COD_FORNECEDOR_F
INNER JOIN DIM_O_QUE_PRODUTO ON COD_PRODUTO = COD_PRODUTO_F
INNER JOIN DIM_QUEM_VENDEU ON COD_MATRICULA = COD_MATRICULA_F
GROUP BY NOME_FORNECEDOR,NOME_PRODUTO,NOME_VEND
ORDER BY QUANTIDADE_VENDIDA DESC

-- 7) PEÇA QUE MAIS VENDEU NO ANO
SELECT NOME_PRODUTO, NOME_FORNECEDOR,SUM (VALOR_VENDA-CUSTO_VENDA) AS LUCRO_LIQUIDO, COUNT (*) AS QUANITDADE_VENDIDA, ANO FROM DIM_FATO_VENDAS
INNER JOIN DIM_O_QUE_PRODUTO ON COD_PRODUTO = COD_PRODUTO_F
INNER JOIN DIM_QUANDO_VENDEU ON COD_QUANDO_VENDEU = COD_QUANDO_VENDEU_F
INNER JOIN DIM_QUEM_FORNECEU ON COD_FORNECEDOR = COD_FORNECEDOR_F
GROUP BY NOME_PRODUTO,NOME_FORNECEDOR,ANO
ORDER BY LUCRO_LIQUIDO DESC

--8) PEÇA CARRO E ANO DO CARRO QUE MAIS RETORNA LUCRO 
SELECT NOME_FORNECEDOR, NOME_PRODUTO, APLICACAO_PRODUTO, ANO AS ANO_CARRO, COUNT (*) AS QUANTIDADE, SUM (VALOR_VENDA-CUSTO_VENDA) LUCRO_LIQUIDO FROM DIM_FATO_VENDAS
INNER JOIN DIM_O_QUE_PRODUTO ON COD_PRODUTO = COD_PRODUTO_F
INNER JOIN DIM_QUEM_FORNECEU ON COD_FORNECEDOR = COD_FORNECEDOR_F
INNER JOIN DIM_QUANDO_VENDEU ON COD_QUANDO_VENDEU = COD_QUANDO_VENDEU_F
GROUP BY NOME_FORNECEDOR,NOME_PRODUTO,APLICACAO_PRODUTO,ANO
ORDER BY LUCRO_LIQUIDO DESC














